
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

// #include "config.h"
#include "json-enum-types.h"
#include "json-builder.h"
#include "json-generator.h"
#include "json-gobject.h"
#include "json-gvariant.h"
#include "json-parser.h"
#include "json-path.h"
#include "json-reader.h"
#include "json-types.h"
#include "json-utils.h"
#include "json-version-macros.h"

#define C_ENUM(v) ((gint) v)
#define C_FLAGS(v) ((guint) v)

/* enumerations from "json-parser.h" */

GType
json_parser_error_get_type (void)
{
static gsize gtype_id = 0;
static const GEnumValue values[] = {
    { C_ENUM(JSON_PARSER_ERROR_PARSE), "JSON_PARSER_ERROR_PARSE", "parse" },
    { C_ENUM(JSON_PARSER_ERROR_TRAILING_COMMA), "JSON_PARSER_ERROR_TRAILING_COMMA", "trailing-comma" },
    { C_ENUM(JSON_PARSER_ERROR_MISSING_COMMA), "JSON_PARSER_ERROR_MISSING_COMMA", "missing-comma" },
    { C_ENUM(JSON_PARSER_ERROR_MISSING_COLON), "JSON_PARSER_ERROR_MISSING_COLON", "missing-colon" },
    { C_ENUM(JSON_PARSER_ERROR_INVALID_BAREWORD), "JSON_PARSER_ERROR_INVALID_BAREWORD", "invalid-bareword" },
    { C_ENUM(JSON_PARSER_ERROR_EMPTY_MEMBER_NAME), "JSON_PARSER_ERROR_EMPTY_MEMBER_NAME", "empty-member-name" },
    { C_ENUM(JSON_PARSER_ERROR_INVALID_DATA), "JSON_PARSER_ERROR_INVALID_DATA", "invalid-data" },
    { C_ENUM(JSON_PARSER_ERROR_UNKNOWN), "JSON_PARSER_ERROR_UNKNOWN", "unknown" },
    { C_ENUM(JSON_PARSER_ERROR_NESTING), "JSON_PARSER_ERROR_NESTING", "nesting" },
    { C_ENUM(JSON_PARSER_ERROR_INVALID_STRUCTURE), "JSON_PARSER_ERROR_INVALID_STRUCTURE", "invalid-structure" },
    { C_ENUM(JSON_PARSER_ERROR_INVALID_ASSIGNMENT), "JSON_PARSER_ERROR_INVALID_ASSIGNMENT", "invalid-assignment" },
{ 0, NULL, NULL }
        };
        if (g_once_init_enter (&gtype_id)) {
            GType new_type = g_enum_register_static (g_intern_static_string ("JsonParserError"), values);
            g_once_init_leave (&gtype_id, new_type);
        }
        return (GType) gtype_id;
        }

/* enumerations from "json-path.h" */

GType
json_path_error_get_type (void)
{
static gsize gtype_id = 0;
static const GEnumValue values[] = {
    { C_ENUM(JSON_PATH_ERROR_INVALID_QUERY), "JSON_PATH_ERROR_INVALID_QUERY", "query" },
{ 0, NULL, NULL }
        };
        if (g_once_init_enter (&gtype_id)) {
            GType new_type = g_enum_register_static (g_intern_static_string ("JsonPathError"), values);
            g_once_init_leave (&gtype_id, new_type);
        }
        return (GType) gtype_id;
        }

/* enumerations from "json-reader.h" */

GType
json_reader_error_get_type (void)
{
static gsize gtype_id = 0;
static const GEnumValue values[] = {
    { C_ENUM(JSON_READER_ERROR_NO_ARRAY), "JSON_READER_ERROR_NO_ARRAY", "no-array" },
    { C_ENUM(JSON_READER_ERROR_INVALID_INDEX), "JSON_READER_ERROR_INVALID_INDEX", "invalid-index" },
    { C_ENUM(JSON_READER_ERROR_NO_OBJECT), "JSON_READER_ERROR_NO_OBJECT", "no-object" },
    { C_ENUM(JSON_READER_ERROR_INVALID_MEMBER), "JSON_READER_ERROR_INVALID_MEMBER", "invalid-member" },
    { C_ENUM(JSON_READER_ERROR_INVALID_NODE), "JSON_READER_ERROR_INVALID_NODE", "invalid-node" },
    { C_ENUM(JSON_READER_ERROR_NO_VALUE), "JSON_READER_ERROR_NO_VALUE", "no-value" },
    { C_ENUM(JSON_READER_ERROR_INVALID_TYPE), "JSON_READER_ERROR_INVALID_TYPE", "invalid-type" },
{ 0, NULL, NULL }
        };
        if (g_once_init_enter (&gtype_id)) {
            GType new_type = g_enum_register_static (g_intern_static_string ("JsonReaderError"), values);
            g_once_init_leave (&gtype_id, new_type);
        }
        return (GType) gtype_id;
        }

/* enumerations from "json-types.h" */

GType
json_node_type_get_type (void)
{
static gsize gtype_id = 0;
static const GEnumValue values[] = {
    { C_ENUM(JSON_NODE_OBJECT), "JSON_NODE_OBJECT", "object" },
    { C_ENUM(JSON_NODE_ARRAY), "JSON_NODE_ARRAY", "array" },
    { C_ENUM(JSON_NODE_VALUE), "JSON_NODE_VALUE", "value" },
    { C_ENUM(JSON_NODE_NULL), "JSON_NODE_NULL", "null" },
{ 0, NULL, NULL }
        };
        if (g_once_init_enter (&gtype_id)) {
            GType new_type = g_enum_register_static (g_intern_static_string ("JsonNodeType"), values);
            g_once_init_leave (&gtype_id, new_type);
        }
        return (GType) gtype_id;
        }

/* Generated data ends here */

